# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  heroku: circleci/heroku@1.0.1

x-job-default: &defaults
  parallelism: 1
  working_directory: ~/workspace/dt

commands:
  configure_bundler:
    description: "Configures and install correct version of bundler"
    steps:
      - run:
          name: "Config and Install bundler"
          command: |
            APP_BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")
            gem install bundler --version $APP_BUNDLER_VERSION

jobs:
  yarn:
    <<: *defaults
    docker:
      - image: circleci/node:stretch
        environment:
          NODE_ENV: test
          YARN_CACHE_FOLDER: ~/workspace/yarn-cache
    steps:
      - checkout
      - restore_cache:
          keys:
            - dt-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      - run:
         name: "Yarn Install"
         command: yarn install
      - save_cache:
          key: dt-yarn-{{ arch }}-{{ checksum "yarn.lock" }}
          paths: ~/workspace/yarn-cache
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - yarn-cache

  bundle:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.5
    steps:
      - checkout
      - configure_bundler
      - restore_cache:
          keys:
            - dt-bundle-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
      - run:
          name: Bundle Install
          command: bundle install --clean --jobs=1 --retry=2 --deployment
      - save_cache:
          key: dt-bundle-{{ arch }}-{{ checksum ".ruby-version" }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - dt/vendor/bundle

  rspec:
    <<: *defaults
    docker:
      - image: circleci/ruby:2.5.5-node-browsers
        environment:
          RAILS_ENV: test
    steps:
      - checkout
      - configure_bundler
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Display versions
          command: |
            ruby --version
            bundle --version
      - run:
          name: Bundle Install
          command: bundle install --jobs=1 --retry=2 --deployment
      - run:
          name: Yarn Install
          command: yarn install
      - run:
          name: Test
          command: |
            bundle exec rails test
            bundle exec rails test:system

  deploy:
    executor:
      heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          command: |
            echo "Starting deploy" ${CIRCLE_BRANCH}
      - heroku/deploy-via-git
      - run:
          command: |
            echo "Finished deploying" ${CIRCLE_BRANCH}
            echo "Revision check etc."

workflows:
  tests:
    jobs:
      - bundle
      - yarn
      - rspec:
          requires:
            - bundle
            - yarn
      - deploy:
          requires:
            - rspec
          filters:
            branches:
              only:
                - master
